name: HCLives
version: 1.0
authors: [CPx1989]
description: Control the amount of lives for Hardcore
main: com.cpx1989.hclives.HCLives
commands:
  hclives:
    description: HCLives
    aliases: hcl
permissions:
  hcl.bypass:
    default: false
  hcl.admin:
    default: false
    children:
      - hcl.reload
      - hcl.check.other
  hcl.check.other:
    default: false
  hcl.reload:
    default: false